import { experiences, faqs, speakers, timeline } from "@/data/siteContent";

const Cta = ({ secondary = false, children = "東松島で参加する" }: { secondary?: boolean; children?: React.ReactNode }) => <a className={`button ${secondary ? "button-secondary" : ""}`} href="#tickets">{children}<span aria-hidden="true">→</span></a>;
const Eyebrow = ({ children }: { children: React.ReactNode }) => <p className="eyebrow">{children}</p>;

export function SummitPage() {
  return <main>
    <header className="site-header"><a href="#top" className="brand"><span>JAPAN</span> REGEN SUMMIT 2026</a><nav aria-label="メインナビゲーション"><a href="#why">開催理由</a><a href="#experience">体験</a><a href="#overview">開催概要</a></nav><a className="header-cta" href="#tickets">参加する</a></header>

    <section className="hero" id="top">
      <video className="hero-video" autoPlay muted loop playsInline poster="/images/hero-fallback.jpg" aria-hidden="true"><source src="/videos/hero-kibotcha.mp4" type="video/mp4" /></video>
      {/* Hero production prompt: A cinematic drone shot over a regenerative summit venue in rural Japan, featuring a former school building transformed into an eco-village, gardens, planting area, small tents, workshop spaces, people gathering on a central lawn, warm morning light, gentle breeze, calm and elegant atmosphere, human and nature in harmony, refined, realistic, non-spiritual, subtle premium documentary tone, slow low-altitude aerial movement, beautiful composition, natural colors. */}
      <div className="hero-fallback" aria-hidden="true"><span className="sun"/><span className="land land-one"/><span className="land land-two"/></div><div className="hero-shade"/>
      <div className="hero-content"><p className="hero-kicker">JAPAN REGEN SUMMIT 2026 · HIGASHIMATSUSHIMA</p><h1><span>Japan リジェンサミット 2026</span>いのち、始まる。</h1><p className="hero-lead">「地球のために我慢する」から、<br/>「あなたが生き生きするほど、地球も豊かになる」へ。</p><p className="hero-body">人と地球が、ともに豊かになっていく未来を体験する1日です。</p><div className="event-meta"><span>2026.9.26 SAT</span><span>宮城県東松島市 KIBOTCHA</span><span>現地＋オンライン</span></div><div className="hero-actions"><Cta>Japan リジェンサミット2026に参加する</Cta><a href="#online" className="text-link">オンライン参加を見る ↓</a></div></div><a href="#why" className="scroll-cue">SCROLL<span/></a>
    </section>

    <section className="manifesto section-pad"><div className="narrow"><Eyebrow>THE DAY WE BEGIN</Eyebrow><p className="big-serif">守るだけじゃない。</p><p>人が関わるほど、自然も、地域も、社会も、もっと豊かになっていくとしたら。</p><div className="verb-line"><span>出会う。</span><span>見る。</span><span>感じる。</span><span>語り合う。</span><span>土に触れる。</span></div><blockquote>「自分は、ここから何を始めよう」</blockquote></div></section>

    <section className="official-visual section-pad" aria-labelledby="official-visual-title"><div className="official-visual-copy"><Eyebrow>OFFICIAL KEY VISUAL</Eyebrow><h2 id="official-visual-title">人が集い、<br/>関係が始まる。</h2><p>この場所で生まれるのは、知識だけではありません。一緒に火を囲み、食べ、話す。その時間から、未来を支える関係が育っていきます。</p></div><figure><img src="/official-key-visual.png" alt="Japan リジェンサミット2026 公式キービジュアル" loading="lazy"/><figcaption>Japan リジェンサミット 2026 公式キービジュアル</figcaption></figure></section>

    <section className="section-pad why" id="why"><div className="section-grid"><div className="sticky-copy"><Eyebrow>WHY HIGASHIMATSUSHIMA</Eyebrow><h2>なぜ今年、<br/>東松島で集まるのか。</h2><p className="lead">備えるということは、怖がりながら生きることではない。</p></div><div className="prose"><p>災害は、「いつか、どこかで起きる話」ではありません。私たちが暮らしているこの国で、今も起きています。</p><p>でも僕たちは、怖がってほしくてこの話をしているわけではありません。むしろ伝えたいのは、その逆です。</p><p>水を備える。食料を備える。電気を備える。それはもちろん大切です。</p><p>でも、本当に何かが起きたとき、自分が知っている場所がある。顔を思い浮かべられる人がいる。「助けて」と言える相手がいる。反対に「あの人は大丈夫だろうか」と気にかけられる相手がいる。</p><p className="emphasis">何も起きていない日に、そんな関係をつくっておく。それもまた、命を守るための大切な備えだと僕たちは考えています。</p></div></div><div className="infrastructure"><article><span>01</span><h3>物資の備え</h3><p>水、食料、暮らしを支えるもの。</p></article><article><span>02</span><h3>エネルギーの備え</h3><p>電気、通信、止まらない仕組み。</p></article><article className="active"><span>03</span><h3>人と場所の備え</h3><p>顔が見える関係と、帰れる場所。</p></article></div></section>

    <section className="relationship section-pad"><div className="narrow center"><Eyebrow>RELATIONSHIP AS INFRASTRUCTURE</Eyebrow><h2>防災は、設備だけじゃない。<br/>関係性も、インフラです。</h2></div><div className="relationship-flow"><span>同じ景色を見る</span><i>—</i><span>名前を知る</span><i>—</i><span>顔を覚える</span><i>—</i><span>支え合える</span></div><div className="narrow prose center-text"><p>道路や電気や水道と同じように、<strong>人と人との関係もまた、これからの社会を支えるインフラになる。</strong></p><p>まず、この場所を知ってほしい。そして、僕たちと出会ってほしい。そこから関係を始めてほしい。</p></div></section>

    <section className="aid section-pad"><div className="section-grid"><div><Eyebrow>CIRCULATION</Eyebrow><h2>「助け合う」は、<br/>もう始まっています。</h2></div><div className="prose"><p>東日本大震災で、多くの支援を受けた東松島から、今度は困っている誰かのもとへ向かう。受け取ったものを、次の誰かへ渡していく。</p><p className="emphasis">人と人の間にも、再生する循環はつくれる。</p><p>助けてもらった人が、いつか誰かを助ける人になる。出会った人が、次の人をつなぐ。ひとつの地域で生まれた知恵が、別の地域の命を守る。</p></div></div></section>

    <section className="kibotcha section-pad" id="kibotcha"><div className="kibotcha-visual" aria-label="KIBOTCHA会場写真の差し替え領域"><span>KIBOTCHA<br/>SMART ECO-VILLAGE</span></div><div className="kibotcha-copy"><Eyebrow>ABOUT KIBOTCHA</Eyebrow><h2>会場そのものが、<br/>「いのちの再生」を体現しています。</h2><p>東日本大震災で大きな被害を受けた、旧東松島市立野蒜小学校。学校としての役割を終えた場所は、防災を学び、人が泊まり、子どもが遊び、人と人が出会い、未来の暮らしを実験する場所へ生まれ変わりました。</p><p>目指すのは、平常時には人と自然がともに暮らす未来をつくり、災害時には<strong>1万人の命を守る防災拠点</strong>として機能する、循環型のスマートエコビレッジ。</p><p className="emphasis">ここは、完成した理想郷ではありません。まだつくっている途中です。だからこそ、未来がつくられていく途中に、自分も関われます。</p><div className="mini-flow"><span>旧野蒜小学校<small>BEFORE</small></span><i>→</i><span>KIBOTCHA<small>NOW</small></span><i>→</i><span>命を守る村<small>FUTURE</small></span></div></div></section>

    <section className="comparison section-pad"><div className="narrow center"><Eyebrow>FROM SUSTAINABLE TO REGENERATIVE</Eyebrow><h2>「地球のために我慢する」。<br/>それだけが、本当に答えでしょうか。</h2><p>守ることも大切です。でも僕たちは、その先にもう一つの可能性があると思っています。</p></div><div className="compare-cards"><article><p>SUSTAINABLE<span>サステナブル（持続可能）</span></p><h3>これ以上、<br/>悪くしない。</h3><ul><li>ゴミを減らす</li><li>資源を大切に使う</li><li>森をこれ以上減らさない</li></ul></article><article className="regen-card"><p>REGENERATIVE<span>リジェネラティブ（再生型）</span></p><h3>もっと豊かに<br/>できないか。</h3><ul><li>土が豊かになる</li><li>生き物と地域の仕事が増える</li><li>新しい循環を生み出す</li></ul></article></div><div className="narrow prose"><p>どちらかが正しくて、どちらかが間違っているわけではありません。サステナブルという大切な考え方が広がってきたからこそ、その先へ進みたい。</p><blockquote>もし、人間が地球にいることそのものが、「プラス」になるとしたら。</blockquote><p>人が食べることで土が豊かになる。働くことで地域が元気になる。学ぶことで次の世代の選択肢が増える。出会うことで新しいプロジェクトが始まり、つながることで、もしもの時に支え合えるようになる。</p></div></section>

    <section className="experience section-pad" id="experience"><div className="section-heading"><div><Eyebrow>EXPERIENCE</Eyebrow><h2>9月26日。<br/>ここでしかできない体験。</h2></div><p>セッションだけが、サミットではありません。食べる時間も、歩く時間も、土に触れる時間も、夜に語る時間も。</p></div><div className="experience-grid">{experiences.map(([tag,title,text],i)=><article key={title}><span className="card-number">0{i+1}</span>{i === 1 ? <div className="experience-media"><video autoPlay muted loop playsInline preload="metadata" aria-hidden="true"><source src="/videos/experience-dialogue.mp4" type="video/mp4" /></video></div> : <div className={`photo-placeholder photo-${i+1}`}><small>IMAGE / VIDEO</small></div>}<p className="eyebrow">{tag}</p><h3>{title}</h3><p>{text}</p></article>)}</div><div className="mid-cta"><p>画面越しではなく、この場所の空気に触れてほしい。</p><Cta/></div></section>

    <section className="schedule section-pad"><div className="section-heading"><div><Eyebrow>DAY SCHEDULE</Eyebrow><h2>当日の過ごし方</h2></div><p>時間はデモ版の予定です。最新情報は順次更新します。</p></div><div className="timeline">{timeline.map(([time,title])=><div key={`${time}-${title}`}><time>{time}</time><span/><p>{title}</p></div>)}</div></section>

    <section className="speakers section-pad"><div className="section-heading"><div><Eyebrow>SPEAKERS & PRACTITIONERS</Eyebrow><h2>この日、出会える<br/>実践者たち。</h2></div><p>登壇者は今後も順次アップデート予定です。</p></div><div className="speaker-grid">{speakers.map(([name,role,text],i)=><article key={name}><div className={`portrait portrait-${i+1}`}><span>{name.slice(0,1)}</span></div><h3>{name}<small>氏</small></h3><p className="role">{role}</p><p>{text}</p></article>)}</div></section>

    <section className="for-you section-pad"><div className="narrow center"><Eyebrow>FOR YOU</Eyebrow><h2>こんな人に来てほしい。</h2></div><div className="checks"><p>環境や社会のために何かしたい。でも「我慢しろ」「正しく生きろ」だけには違和感がある。</p><p>自分の仕事を、地域や社会、次の世代の豊かさにつなげたい。</p><p>普段なら会えない分野の人と話してみたい。</p><p>「サステナブルのその先」を、知識ではなく現場で感じたい。</p><p>具体的な活動はまだないけれど、「自分にも何かできる」と感じている。</p><p>防災・地域・農・教育・社会とのつながりを考えたい。</p></div><div className="narrow prose center-text"><p>環境活動家である必要はありません。専門家である必要も、立派な肩書きもいりません。</p><blockquote>自分は、どんな未来なら生きてみたいのか。<br/>そこからでいい。</blockquote></div></section>

    <section className="takeaways section-pad"><div className="narrow center"><Eyebrow>TAKE IT HOME</Eyebrow><h2>この日、持ち帰ってほしい<br/>3つのもの。</h2></div><div className="takeaway-grid"><article><span>01</span><h3>新しい「見方」</h3><p>人がいるからこそ、自然や地域が豊かになる可能性。それは仕事や地域、自分自身を見る目まで変えるかもしれません。</p></article><article><span>02</span><h3>分野を越えた「つながり」</h3><p>普段なら同じ場所に集まらない人たちが出会い、新しい活動や、いつか互いを支え合う関係が始まります。</p></article><article><span>03</span><h3>自分から始まる「一歩」</h3><p>誰かに言われた正解ではなく、自分の中から「やってみたい」と思える一つを持ち帰ってください。</p></article></div></section>

    <section className="next-day section-pad"><div className="section-grid"><div><Eyebrow>SEPTEMBER 27 · SIDE EVENT</Eyebrow><h2>そして翌日、<br/>本当に「始める」。</h2></div><div className="prose"><p>希望者向けに、<strong>「リジェンファーム東松島」の発足、種まき体験など</strong>を予定しています。</p><p>前日に未来について話す。翌日、実際に土に触れる。話して終わるのではなく、本当に一粒の種をまく。</p><p className="emphasis">「いのち、始まる。」という言葉が、象徴ではなく、目の前の現実になる時間です。</p></div></div></section>

    <section className="venue-map section-pad"><div className="section-heading"><div><Eyebrow>VENUE EXPERIENCE MAP</Eyebrow><h2>ここを、共に歩きたい。</h2></div><p>人と自然と地域の営みが、ひとつの場所で交わります。</p></div><div className="map-canvas" role="img" aria-label="KIBOTCHA会場体験マップ（デモ）"><div className="map-stream"/><div className="map-path path-a"/><div className="map-path path-b"/><span className="map-tree t1">♧</span><span className="map-tree t2">♧</span><span className="map-tree t3">♧</span><div className="map-place school">旧校舎・ドミトリー<small>STAY</small></div><div className="map-place stage">中央ステージ<small>LISTEN</small></div><div className="central-lawn"><span>中央広場</span><small>REST · MEET · TALK</small></div><div className="map-place farm">畑・温室<small>GROW</small></div><div className="map-place plant">植樹エリア<small>PLANT</small></div><div className="map-place food">フード・BBQ<small>EAT</small></div><div className="map-place market">交流・マーケット<small>CONNECT</small></div><div className="map-place workshop">ワークショップ<small>CREATE</small></div><div className="map-entrance">ENTRANCE ↑</div></div><p className="map-caption">現地完成イメージの空間構成をもとにしたデモ図。実際の配置は今後更新します。</p></section>

    <section className="ark section-pad"><div className="narrow center"><Eyebrow>MORE THAN ONE DAY</Eyebrow><h2>僕たちがつくりたいのは、<br/>1日だけのイベントではありません。</h2><p>平時には、人が集い、遊び、学び、挑戦する。もしもの時には、互いの命を支え合う。</p><blockquote>そんな“命の箱舟”のような<br/>場所と関係を育てていきたい。</blockquote><p>箱舟は、建物だけではつくれません。設備だけでもつくれません。人が必要です。関係が必要です。信頼が必要です。</p></div></section>

    <section className="overview section-pad" id="overview"><div><Eyebrow>EVENT INFORMATION</Eyebrow><h2>開催概要</h2></div><dl><div><dt>名称</dt><dd>Japan リジェンサミット 2026<br/>― いのち、始まる。―</dd></div><div><dt>日時</dt><dd>2026年9月26日（土）</dd></div><div><dt>会場</dt><dd>KIBOTCHA SMART ECO-VILLAGE<br/>宮城県東松島市野蒜字亀岡80番</dd></div><div><dt>形式</dt><dd>オフライン会場＋オンライン同時開催</dd></div><div><dt>主催</dt><dd>任意団体 日本リジェネラティブ協会</dd></div><div><dt>翌日</dt><dd>リジェンファーム東松島発足・種まき体験など</dd></div></dl></section>

    <section className="tickets section-pad" id="tickets"><div className="narrow center"><Eyebrow>TICKETS</Eyebrow><h2>参加方法・チケット</h2><p>できるなら、今回は東松島へ来てください。会わなければ始まらない関係があります。</p></div><div className="ticket-grid"><article className="recommended"><span className="badge">RECOMMENDED</span><p className="eyebrow">ON-SITE</p><h3>現地で参加する</h3><p className="price">¥4,500〜<small>一般</small></p><ul><li>大学生・専門学生 1,000円〜</li><li>高校生以下 イベント参加無料〜</li><li>BBQ付きプラン</li><li>旧校舎ドミトリー宿泊付きプラン</li></ul><Cta>チケットを申し込む</Cta></article><article id="online"><p className="eyebrow">ONLINE</p><h3>オンラインで参加する</h3><p className="price">¥1,000<small>一般</small></p><ul><li>学生 500円</li><li>当日のセッションを配信</li><li>遠方から参加可能</li></ul><Cta secondary>オンライン参加を見る</Cta></article></div><p className="ticket-note">※デモ版の価格・プラン表示です。正式なチケットURLと詳細は後日差し替えます。</p></section>

    <section className="faq section-pad"><div className="section-grid"><div><Eyebrow>FAQ</Eyebrow><h2>よくあるご質問</h2></div><div className="faq-list">{faqs.map(([q,a],i)=><details key={q} open={i===0}><summary>{q}<span>＋</span></summary><p>{a}</p></details>)}</div></div></section>

    <section className="final-cta section-pad"><div className="narrow center"><Eyebrow>JAPAN REGEN SUMMIT 2026</Eyebrow><p className="big-serif">いのち、始まる。</p><h2>未来に何かが起きた時に、<br/>支え合える関係を、<br/>何も起きていない今からつくる。</h2><p>まだ名前のついていない未来に、一緒に会いに行きませんか。</p><blockquote>あなたが生き生きするほど、<br/>地球も、地域も、人も豊かになる。</blockquote><p>まず会いましょう。一緒に食べましょう。話しましょう。土に触れましょう。ここから、関係を始めましょう。</p><div className="final-meta">2026年9月26日（土）<br/>宮城県東松島市 KIBOTCHA</div><div className="hero-actions"><Cta>Japan リジェンサミット2026に参加する</Cta><a href="#online" className="text-link light">オンライン参加を見る</a></div></div></section>

    <footer><p>JAPAN REGEN SUMMIT 2026</p><small>主催：任意団体 日本リジェネラティブ協会</small></footer><div className="mobile-cta"><a href="#tickets">東松島で参加する <span>→</span></a></div>
  </main>;
}
